version: '3.8'
services:
    laravel:
        container_name: todo_app_rest_api
        build:
            context: .
            dockerfile: Dockerfile
        command: 'php artisan serve --host=0.0.0.0'
        volumes:
            - ./:/app
        ports:
            - 8000:8000
        networks:
            - todolist
        depends_on:
            - db
    db:
        container_name: todo_app_db
        image: mysql:8.0
        environment:
            MYSQL_DATABASE: todolist
            MYSQL_USER: admin
            MYSQL_ROOT: admin
            MYSQL_PASSWORD: admin
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./.mysql:/var/lib/mysql
        ports:
            - 3306:3306
        networks:
            - todolist
networks:
    todolist:
